-- MySQL Script generated by MySQL Workbench
-- Mon Dec 19 11:09:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApellidoP` VARCHAR(45) NOT NULL,
  `ApellidoM` VARCHAR(45) NULL,
  `Edad` INT NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nivel_Academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nivel_Academico` (
  `idNivel_Academico` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(60) NULL,
  PRIMARY KEY (`idNivel_Academico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(60) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesores` (
  `Matricula_Profesor` VARCHAR(10) NOT NULL,
  `idNivel_Academico` INT NULL,
  `idPersona` INT NULL,
  `idCategoria` INT NULL,
  PRIMARY KEY (`Matricula_Profesor`),
  INDEX `idNivel_Academico_idx` (`idNivel_Academico` ASC) VISIBLE,
  INDEX `idPersona_idx` (`idPersona` ASC) VISIBLE,
  INDEX `idCategoria_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `idNivel_Academico`
    FOREIGN KEY (`idNivel_Academico`)
    REFERENCES `mydb`.`Nivel_Academico` (`idNivel_Academico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPersona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumnos` (
  `Matricula_Alumno` VARCHAR(10) NOT NULL,
  `Carrera` VARCHAR(45) NULL,
  `Semestre` INT NULL,
  `idNivel_Academico` INT NULL,
  `idPersona` INT NULL,
  `idCategoria` INT NULL,
  `Matricula_Profesor` VARCHAR(10) NULL,
  PRIMARY KEY (`Matricula_Alumno`),
  INDEX `idPersona_idx` (`idPersona` ASC) VISIBLE,
  INDEX `idNivel_Academico_idx` (`idNivel_Academico` ASC) VISIBLE,
  INDEX `idCategoria_idx` (`idCategoria` ASC) VISIBLE,
  INDEX `Matricula_Profesor_idx` (`Matricula_Profesor` ASC) VISIBLE,
  CONSTRAINT `idPersona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idNivel_Academico`
    FOREIGN KEY (`idNivel_Academico`)
    REFERENCES `mydb`.`Nivel_Academico` (`idNivel_Academico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Matricula_Profesor`
    FOREIGN KEY (`Matricula_Profesor`)
    REFERENCES `mydb`.`Profesores` (`Matricula_Profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrada_Salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrada_Salida` (
  `idEntrada_Salida` INT NOT NULL AUTO_INCREMENT,
  `Hora_entrada` TIME NULL,
  `Hora_salida` TIME NULL,
  `En_uso` TINYINT NULL,
  `Matricula_Alumno` VARCHAR(10) NULL,
  `Matricula_Profesor` VARCHAR(10) NULL,
  `idCategoria` INT NULL,
  PRIMARY KEY (`idEntrada_Salida`),
  INDEX `Matricula_Alumno_idx` (`Matricula_Alumno` ASC) VISIBLE,
  INDEX `Matricula_Profesor_idx` (`Matricula_Profesor` ASC) VISIBLE,
  INDEX `idCategoria_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `Matricula_Alumno`
    FOREIGN KEY (`Matricula_Alumno`)
    REFERENCES `mydb`.`Alumnos` (`Matricula_Alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Matricula_Profesor`
    FOREIGN KEY (`Matricula_Profesor`)
    REFERENCES `mydb`.`Profesores` (`Matricula_Profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`No_Autorizados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`No_Autorizados` (
  `idNo_Autorizados` INT NOT NULL,
  `Fecha` DATE NULL,
  `Hora` TIME NULL,
  PRIMARY KEY (`idNo_Autorizados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `Matricula_Administrador` VARCHAR(10) NOT NULL,
  `idPersona` INT NULL,
  `idCategoria` INT NULL,
  `idNivel_Academico` INT NULL,
  `idNo_Autorizado` INT NULL,
  PRIMARY KEY (`Matricula_Administrador`),
  INDEX `idPersona_idx` (`idPersona` ASC) VISIBLE,
  INDEX `idCategoria_idx` (`idCategoria` ASC) VISIBLE,
  INDEX `idNivel_Academico_idx` (`idNivel_Academico` ASC) VISIBLE,
  INDEX `idNo_Autorizado_idx` (`idNo_Autorizado` ASC) VISIBLE,
  CONSTRAINT `idPersona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idNivel_Academico`
    FOREIGN KEY (`idNivel_Academico`)
    REFERENCES `mydb`.`Nivel_Academico` (`idNivel_Academico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idNo_Autorizado`
    FOREIGN KEY (`idNo_Autorizado`)
    REFERENCES `mydb`.`No_Autorizados` (`idNo_Autorizados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
